/*
 * presets5.js: the five inch tracks that ship with the builder, and nothing else.
 *
 * GENERATED by scripts/mission-preset.js from the short list in that file. Edit the list and run the script; do not
 * edit this file by hand. It is the builder's alone: src/trackbuilder/app.js hands it to storage.js (shipTracks),
 * so the simulator's own boot graph does not carry it.
 *
 * Copyright (C) 2026 WebFPVSimulator contributors
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * THE 2026 AUSTRALIAN DRONE NATIONALS QUALIFYING TRACK, laid out from the designer's plan. Credit goes to the
 * designer and the event, as the plan names them; the sponsor's mark is not on it.
 */
export const FIVE_INCH_PRESETS = [
  {
    "schemaVersion": 3,
    "id": "nationals-2026-qualifier",
    "name": "Drone Nationals 2026 qualifier",
    "createdUtc": "2026-10-01T00:00:00Z",
    "modifiedUtc": "2026-10-01T00:00:00Z",
    "trackClass": "full",
    "field": {
      "width": 45,
      "depth": 55,
      "gridSize": 1
    },
    "settings": {
      "tangentScale": 1.1,
      "minCurveRadius": 1,
      "samplesPerSegment": 48
    },
    "branding": {
      "logos": []
    },
    "credit": {
      "designer": "Wilf",
      "series": "2026 Mission Foods Australian Drone Nationals, official qualifying track",
      "sponsor": "",
      "source": "the official layout and dimensions plan",
      "broughtOverBy": "",
      "note": "Rebuilt in the builder from the plan, for practice. It is not the organisers' file."
    },
    "elements": [
      {
        "id": "el-1",
        "type": "gate",
        "name": "Start and finish",
        "position": {
          "x": 20,
          "y": 19,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913
        }
      },
      {
        "id": "el-2",
        "type": "barrier",
        "name": "Hurdle",
        "position": {
          "x": 27,
          "y": 28,
          "z": 0
        },
        "yaw": 3.141593,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "width": 4,
          "depth": 0.1,
          "height": 1,
          "flagH": 2
        },
        "flagSide": "both"
      },
      {
        "id": "el-3",
        "type": "waypoint",
        "name": "Over the hurdle",
        "position": {
          "x": 27,
          "y": 28,
          "z": 2
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-4",
        "type": "flaggedGate",
        "name": "East spiral gate",
        "position": {
          "x": 30,
          "y": 35,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913,
          "flagH": 1.45
        },
        "flagSide": "both"
      },
      {
        "id": "el-5",
        "type": "waypoint",
        "name": "Spiral right",
        "position": {
          "x": 28.547,
          "y": 33.88,
          "z": 3.353
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-6",
        "type": "waypoint",
        "name": "Spiral right",
        "position": {
          "x": 30.307,
          "y": 34.968,
          "z": 3.17
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-7",
        "type": "waypoint",
        "name": "Spiral right",
        "position": {
          "x": 31.484,
          "y": 33.267,
          "z": 2.591
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-8",
        "type": "waypoint",
        "name": "Spiral right",
        "position": {
          "x": 29.846,
          "y": 32.004,
          "z": 2.011
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-9",
        "type": "waypoint",
        "name": "Spiral right",
        "position": {
          "x": 28.5,
          "y": 33.575,
          "z": 1.432
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-10",
        "type": "diveGate",
        "name": "Up gate",
        "position": {
          "x": 33,
          "y": 43,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0.785398,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 1.5,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.862201
        }
      },
      {
        "id": "el-11",
        "type": "waypoint",
        "name": "Over the top",
        "position": {
          "x": 31,
          "y": 48,
          "z": 3.5
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-12",
        "type": "flaggedGate",
        "name": "Bay 1",
        "position": {
          "x": 23,
          "y": 43,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913,
          "flagH": 1.45
        },
        "flagSide": "right",
        "group": "grp-1",
        "style": "plain"
      },
      {
        "id": "el-13",
        "type": "gate",
        "name": "Bay 2",
        "position": {
          "x": 21,
          "y": 43,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913
        },
        "unbuiltSides": [
          "right"
        ],
        "group": "grp-1",
        "style": "plain"
      },
      {
        "id": "el-14",
        "type": "gate",
        "name": "Bay 3",
        "position": {
          "x": 19,
          "y": 43,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913
        },
        "unbuiltSides": [
          "right"
        ],
        "group": "grp-1",
        "style": "plain"
      },
      {
        "id": "el-15",
        "type": "waypoint",
        "name": "Round the flag",
        "position": {
          "x": 24.707,
          "y": 42.248,
          "z": 0.853
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-16",
        "type": "waypoint",
        "name": "Round the flag",
        "position": {
          "x": 23.608,
          "y": 42.067,
          "z": 0.853
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-17",
        "type": "waypoint",
        "name": "Out of the wall",
        "position": {
          "x": 16,
          "y": 45,
          "z": 2
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-18",
        "type": "flaggedGate",
        "name": "West spiral gate",
        "position": {
          "x": 5,
          "y": 29,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913,
          "flagH": 1.45
        },
        "flagSide": "right"
      },
      {
        "id": "el-19",
        "type": "waypoint",
        "name": "Spiral left",
        "position": {
          "x": 3.882,
          "y": 31.506,
          "z": 3.432
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-20",
        "type": "waypoint",
        "name": "Spiral left",
        "position": {
          "x": 3.85,
          "y": 29.535,
          "z": 3.318
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-21",
        "type": "waypoint",
        "name": "Spiral left",
        "position": {
          "x": 5.797,
          "y": 29.229,
          "z": 3.035
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-22",
        "type": "waypoint",
        "name": "Spiral left",
        "position": {
          "x": 6.372,
          "y": 31.114,
          "z": 2.49
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-23",
        "type": "waypoint",
        "name": "Spiral left",
        "position": {
          "x": 4.585,
          "y": 31.946,
          "z": 1.944
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-24",
        "type": "waypoint",
        "name": "Spiral left",
        "position": {
          "x": 3.512,
          "y": 30.293,
          "z": 1.398
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-25",
        "type": "waypoint",
        "name": "Turn south",
        "position": {
          "x": 7,
          "y": 26,
          "z": 0.9
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-26",
        "type": "waypoint",
        "name": "Swing out",
        "position": {
          "x": 3,
          "y": 23,
          "z": 0.9
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "height": 1.6,
          "poleRadius": 0.02,
          "clearance": 0
        }
      },
      {
        "id": "el-27",
        "type": "flaggedGate",
        "name": "Lower gate",
        "position": {
          "x": 5,
          "y": 19,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 1.705729,
          "clearH": 1.705729,
          "levelPitch": 1.73913,
          "flagH": 1.45
        },
        "flagSide": "both"
      },
      {
        "id": "el-28",
        "type": "flag",
        "name": "Turn flag",
        "position": {
          "x": 5,
          "y": 5,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 2.5,
          "poleRadius": 0.025,
          "clearance": 1.5
        }
      },
      {
        "id": "el-29",
        "type": "startPads",
        "name": "",
        "position": {
          "x": 17,
          "y": 19,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": false,
        "dims": {
          "pads": 4,
          "spacing": 1.5,
          "padSize": 0.6
        }
      }
    ],
    "sequence": [
      {
        "id": "sq-1",
        "elementId": "el-1",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-2",
        "elementId": "el-3",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-4",
        "elementId": "el-5",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-5",
        "elementId": "el-6",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-6",
        "elementId": "el-7",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-7",
        "elementId": "el-8",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-8",
        "elementId": "el-9",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-3",
        "elementId": "el-4",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-9",
        "elementId": "el-10",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-10",
        "elementId": "el-11",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-14",
        "elementId": "el-15",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-15",
        "elementId": "el-16",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-11",
        "elementId": "el-12",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-12",
        "elementId": "el-13",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-13",
        "elementId": "el-14",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-16",
        "elementId": "el-17",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-18",
        "elementId": "el-19",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-19",
        "elementId": "el-20",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-20",
        "elementId": "el-21",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-21",
        "elementId": "el-22",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-22",
        "elementId": "el-23",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-23",
        "elementId": "el-24",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-17",
        "elementId": "el-18",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-24",
        "elementId": "el-25",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-25",
        "elementId": "el-26",
        "apertureIndex": null,
        "entry": null,
        "passSide": "right",
        "clearance": 0,
        "overridden": false
      },
      {
        "id": "sq-26",
        "elementId": "el-27",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-27",
        "elementId": "el-28",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 2.5,
        "overridden": false
      },
      {
        "id": "sq-28",
        "elementId": "el-27",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      }
    ]
  },
];
