/*
 * noun-lint.js: the player only ever sees "track", never "course", and one
 * name for every other thing (MENUS-PLAN.md, the glossary).
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * ONE WORD FOR ONE THING.
 *
 * "Track" was a map id, a menu row, a screen title and a mode, and the same
 * object was a "course" on the board and in the builder's prose. The board's
 * own empty state used both nouns in one sentence. A player cannot be
 * expected to work out that the thing they built, the thing they published
 * and the thing they are racing are the same object when the product calls
 * it two things.
 *
 * The rename is done. This is what stops it coming back, because it will:
 * the next screen somebody adds will say "course" if nothing objects.
 *
 * WHAT THIS CHECKS, and what it deliberately does not.
 *
 * Player-visible text only: string literals that reach the DOM, and HTML
 * text nodes and rendering attributes. NOT identifiers, screen ids, CSS
 * class names, storage keys or API routes. `activeCourseSummary` and
 * `.course-card` are fine: nobody reads them but us, and renaming a stored
 * key would orphan every track already in somebody's browser.
 *
 * Comments are not checked either. They are for whoever is reading the
 * code, and a comment explaining why a key is still spelled `course` has to
 * be allowed to say the word.
 */

import { readdir, readFile } from 'node:fs/promises';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

/* Directories that are not the product: vendored source, build output,
 * scratch, an agent's working copies under .claude, and the test suites,
 * whose names describe code rather than addressing a player. */
const SKIP_DIRS = new Set(['node_modules', '.git', '.loop', '.claude', 'vendor', 'dist', 'tests', 'tmp']);

/*
 * Sightings that are allowed, with their reasons, because a blanket rule
 * that cannot be argued with gets switched off rather than obeyed.
 *
 * It was empty from 2026-08-30 to 2026-10-01. The one entry before that
 * was "FINA 50 m course" in Municipal baths' reference table: the swimming
 * term, long course as
 * against short course, and the real world figure the world-scale check
 * measured that pool against. That map was removed on 2026-08-30 and the
 * exception went with it. An exception outliving the file it excuses is
 * how a list like this stops meaning anything.
 */
const ALLOWED = [
  /*
   * The header racegow-lattice.js writes at the top of the presets.js it
   * generates: a source comment in the file it makes, read by whoever opens
   * that file, never by a player. It says leaderboard in passing, and
   * changing it here would leave the committed presets.js disagreeing with
   * its generator until somebody reran it.
   */
  { file: 'scripts/racegow-lattice.js', text: 'GENERATED by scripts/racegow-lattice.js' },
];

const WORD = /(?<![A-Za-z0-9_])[Cc]ourses?(?![A-Za-z0-9_])/;

/*
 * THE RETIRED NAMES (MENUS-PLAN.md 0.3, the glossary), and the name each
 * gave way to. The menus had grown three names for the board, two for the
 * builder and two for the physics switch, because nothing failed when a new
 * row used an old word. Each of these was a live label or a sentence on
 * 2026-10-01. Same rules as the noun above: player visible text only.
 *
 * And ONE DOOR, ONE NAME, BOTH SIDES (5.4): the board calls itself Tracks
 * and times, so any "Tracks and" that goes on to say something else is a
 * door labelled differently from the room it opens.
 */
const RETIRED = [
  { re: /Tracks and (?!times\b)[A-Za-z]/, use: 'Tracks and times, the board\'s own name for itself' },
  { re: /\bOpen on the web\b/, use: 'This track on Tracks and times' },
  { re: /\bUpload (a time|new best)\b/, use: 'Post a time' },
  { re: /\bRace the record\b/, use: 'Chase the record' },
  { re: /\b(Map|Track) builder\b/, use: 'Builder' },
  { re: /\btrack builder\b/, use: 'the builder' },
  { re: /\bBuild a freestyle map\b/, use: 'Build a map' },
  { re: /\bFreestyle city\b/, use: 'The town' },
  { re: /\bPhysics model\b/, use: 'Flight model' },
  { re: /\bEvery setting\b/, use: 'Firmware bench' },
  { re: /\bFlight controller screen\b/, use: 'Firmware bench' },
  { re: /\b[Tt]he three cards\b/, use: 'What to fly' },
  { re: /\b[Ll]eaderboard\b/, use: 'Tracks and times, or the board' },
];

/* Every problem with one piece of visible text, the noun and the retired
 * names together. */
function offences(visible) {
  const out = [];
  if (WORD.test(visible)) {
    out.push('course: use track');
  }
  for (const r of RETIRED) {
    const m = visible.match(r.re);
    if (m) {
      out.push(`${m[0].trim()}: use ${r.use}`);
    }
  }
  return out;
}

/*
 * Strip comments, then hand back the string literals. Written as a small
 * scanner rather than a regex because a regex cannot tell an apostrophe in
 * a comment from the start of a string, and this file's whole job is to be
 * trusted about which text a player reads.
 */
function literals(src) {
  const out = [];
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    if (c === '"' || c === "'" || c === '`') {
      let j = i + 1;
      while (j < n) {
        if (src[j] === '\\') {
          j += 2;
          continue;
        }
        if (src[j] === c) {
          break;
        }
        j += 1;
      }
      out.push({ at: i + 1, text: src.slice(i + 1, Math.min(j, n)) });
      i = j + 1;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      const j = src.indexOf('*/', i + 2);
      i = j < 0 ? n : j + 2;
      continue;
    }
    if (c === '/' && src[i + 1] === '/') {
      const j = src.indexOf('\n', i);
      i = j < 0 ? n : j;
      continue;
    }
    i += 1;
  }
  return out;
}

/*
 * A route, a storage key, a selector, or a list of CSS class names. Every
 * space separated token is lower case and made only of the characters those
 * things are made of, so `screen screen-page screen-courses` is machinery
 * and `A gated course` is prose.
 */
function isMachineText(text) {
  const tokens = text.trim().split(/\s+/).filter(Boolean);
  if (!tokens.length) {
    return true;
  }
  return tokens.every((t) => /^[a-z0-9\-_./#?=&:]+$/.test(t));
}

/*
 * Blank out every ${...} in a template literal.
 *
 * What is inside one is CODE, not text: `${card.course.track.id}` puts the
 * word in front of this check while putting nothing in front of a player.
 * Reading a property name as prose is the single biggest way this lint
 * could earn a reputation for crying wolf, and a lint with that reputation
 * gets switched off rather than obeyed.
 */
function stripInterpolations(text) {
  return text.replace(/\$\{[^}]*\}/g, '');
}

async function walk(dir, out) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) {
        continue;
      }
      await walk(join(dir, entry.name), out);
      continue;
    }
    if (/\.(js|html)$/.test(entry.name)) {
      out.push(join(dir, entry.name));
    }
  }
  return out;
}

function lineOf(src, at) {
  return src.slice(0, at).split('\n').length;
}

async function main() {
  const files = await walk(root, []);
  const findings = [];
  let scanned = 0;

  for (const file of files) {
    const rel = relative(root, file);
    /* This file names the word it is looking for, dozens of times. */
    if (rel === 'scripts/noun-lint.js') {
      continue;
    }
    /*
     * A selftest's own check names describe code, not a player. So do the
     * check harnesses under scripts/: they drive the shell by its INTERNAL
     * screen ids, `ui.show('courses')`, and they carry that code inside
     * template literals handed to page.evaluate, where it is indistinguishable
     * from prose to anything reading strings. Those ids are deliberately
     * not policed by this lint, so the harnesses that quote them are not
     * either.
     *
     * Anything under scripts/ that GENERATES player-visible output, icons.js
     * and og.js among them, is still scanned: only the -check.js harnesses
     * are skipped, and only because their whole job is to name internals.
     */
    if (/selftest\.js$/.test(rel) || /^scripts\/[a-z-]+-check\.js$/.test(rel)) {
      continue;
    }
    const raw = await readFile(file, 'utf8');
    scanned += 1;

    if (rel.endsWith('.html')) {
      /*
       * A <style> block is not text a player reads, and a <script> block is
       * JavaScript, whose literals go through the same scanner as any other
       * file's. Both are blanked here, keeping the line count, so the text
       * node pass sees only what is actually rendered. Without this the
       * whole palette and every inline module came back as prose.
       */
      const keepLines = (m) => '\n'.repeat((m.match(/\n/g) || []).length);
      let src = raw.replace(/<!--[\s\S]*?-->/g, keepLines);
      const inlineScripts = [...src.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)];
      src = src.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, keepLines);
      src = src.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, keepLines);
      for (const sc of inlineScripts) {
        for (const lit of literals(sc[1])) {
          const visible = stripInterpolations(lit.text);
          const bad = isMachineText(visible) ? [] : offences(visible);
          if (bad.length) {
            findings.push({
              rel,
              line: lineOf(raw, sc.index),
              text: `inline script: ${visible.trim().slice(0, 80)}`,
              bad,
            });
          }
        }
      }
      /* Text nodes. */
      for (const m of src.matchAll(/>([^<]+)</g)) {
        const bad = offences(m[1]);
        if (bad.length) {
          findings.push({ rel, line: lineOf(src, m.index), text: m[1].trim().slice(0, 90), bad });
        }
      }
      /* The attributes that render. */
      for (const m of src.matchAll(/(content|placeholder|aria-label|title|alt)="([^"]*)"/g)) {
        const bad = offences(m[2]);
        if (bad.length) {
          findings.push({ rel, line: lineOf(src, m.index), text: `${m[1]}="${m[2].slice(0, 70)}"`, bad });
        }
      }
      continue;
    }

    for (const lit of literals(raw)) {
      const visible = stripInterpolations(lit.text);
      if (isMachineText(visible)) {
        continue;
      }
      const bad = offences(visible);
      if (!bad.length) {
        continue;
      }
      const line = lineOf(raw, lit.at);
      const text = lit.text.trim().replace(/\s+/g, ' ').slice(0, 90);
      if (ALLOWED.some((a) => a.file === rel && lit.text.includes(a.text))) {
        continue;
      }
      findings.push({ rel, line, text, bad });
    }
  }

  console.log(`noun lint: ${scanned} file(s) scanned for a player-visible "course" and ${RETIRED.length} retired names`);
  if (!findings.length) {
    console.log(`  allowed, with reasons in this file: ${ALLOWED.length}`);
    console.log('\nPASS, the player only ever sees a track, and every thing has one name');
    return 0;
  }
  for (const f of findings) {
    console.log(`  ${f.rel}:${f.line}  ${f.text}`);
    console.log(`      ${f.bad.join('; ')}`);
  }
  console.log(`\nFAIL, ${findings.length} player-visible name(s) the glossary retired`);
  console.log('One word for one thing. Use the name given, or add an argued exception to ALLOWED.');
  return 1;
}

process.exit(await main());
